@localhost=http://localhost:8081

###
GET {{localhost}}/
###
GET {{localhost}}/getUserId
###---------
GET {{localhost}}/getDevices?userId=1
###
GET {{localhost}}/getConfig?userId=1
###
GET {{localhost}}/listActions
###
GET {{localhost}}/listRules
###
GET {{localhost}}/listModes

###
POST {{localhost}}/setConfig?userId=1
Content-Type: application/json

{
    "ip": "192.168.178.5"
}

###
POST {{localhost}}/startDevice
Content-Type: application/json

{
    
}


###
POST {{localhost}}/stopDevice
Content-Type: application/json

{
    
}

###
POST {{localhost}}/checkConnection
Content-Type: application/json

{
    
}

###
POST {{localhost}}/startDevice
Content-Type: application/json

{
    
}

###
